language: node_js
node_js:
  - "4"
before_install:
  - npm install -g grunt-cli
install:
  - npm install
  - npm i
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < report/lcov.info
